### ISSUE TITLE
NameError: name 'self' is not defined 

### ISSUE THREAD

**Issue by mkoshti2001** [dmitriiweb/tapy#4]
from tapy import Indicators
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv('banknifty.csv')
indicators = Indicators(df)
indicators.sma()
Indicators.bollinger_bands(self, period=20, deviation=2, column_name_top='bollinger_up', column_name_mid='bollinger_mid', column_name_bottom='bollinger_bottom')
Indicators.atr(period=14, column_name='atr')
Indicators.mfi(period=5, column_name='mfi')
df = indicators.df
df.tail()
df 
while doing this i am getting following error
File "C:\Users\admin\untitled0.py", line 10, in <module>
    Indicators.bollinger_bands(self, period=20, deviation=2, column_name_top='bollinger_up', column_name_mid='bollinger_mid', column_name_bottom='bollinger_bottom')
NameError: name 'self' is not defined

how to solve this error?

**Comment by dmitriiweb** [comment]
Change
`Indicators.bollinger_bands(self, period=20, deviation=2, column_name_top='bollinger_up', column_name_mid='bollinger_mid', `
to
`indicators.bollinger_bands(self, period=20, deviation=2, column_name_top='bollinger_up', column_name_mid='bollinger_mid', `
