### ISSUE TITLE
Using tapy in freqtrade

### ISSUE THREAD

**Issue by maestro73** [dmitriiweb/tapy#5]
I'm trying to use AC but I cannot make it work with freqtrade's Dataframe
The deploy indicators function has the following structure:

def normal_tf_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe['hma_50'] = qtpylib.hull_moving_average(dataframe['close'], window=50)
        dataframe['ema_100'] = ta.EMA(dataframe, timeperiod=100)
        dataframe['ema_28'] = ta.EMA(dataframe, timeperiod=28)
        dataframe['ema_8'] = ta.EMA(dataframe, timeperiod=8)

        #Williams
        #Accelerator
        indicators = Indicators(dataframe)
        indicators.accelerator_oscillator(column_name='AC')
        dataframe['ac'] = indicators.dataframe
        
return dataframe

Can you help me please?

**Comment by maestro73** [comment]
I already changed dataframe['ac'] = indicators.dataframe   for dataframe = indicators.dataframe but it doesn't work.

**Comment by dmitriiweb** [comment]
`
#Williams
#Accelerator
indicators = Indicators(dataframe)
indicators.accelerator_oscillator(column_name='AC')
dataframe['ac'] = indicators.df
`
